version: "3.8"

services:
  library:
    build:
      context: ./library
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  users:
    build:
      context: ./users
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
