basePath: /
host: localhost:8080
info:
  contact: {}
  description: API for managing users data.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Users Service API
  version: "1.0"
paths: {}
swagger: "2.0"
