basePath: /
definitions:
  server.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  server.ResponseUserReading:
    properties:
      authors:
        items:
          type: string
        type: array
      id:
        type: string
      rating:
        type: integer
      status:
        type: string
      title:
        type: string
    type: object
  server.ResponseUserReadingFullInfo:
    properties:
      authors:
        items:
          type: string
        type: array
      finish_date:
        type: string
      id:
        type: string
      rating:
        type: integer
      start_date:
        type: string
      status:
        type: string
      title:
        type: string
    type: object
  server.UserReading:
    properties:
      book_id:
        type: string
      finish_date:
        type: string
      rating:
        type: integer
      start_date:
        type: string
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for managing users' read books.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: User reading Service API
  version: "1.0"
paths:
  /api/authors:
    get:
      consumes:
      - application/json
      description: Gets user reading from DB. Uses access token from an HTTP-only
        cookie
      parameters:
      - description: Reading status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User reading
          schema:
            items:
              $ref: '#/definitions/server.ResponseUserReading'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      summary: Get user reading
      tags:
      - User reading
    post:
      consumes:
      - application/json
      description: Updates user reading in DB. Uses access token from an HTTP-only
        cookie
      parameters:
      - description: Book id with status
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/server.UserReading'
      produces:
      - application/json
      responses:
        "201":
          description: Updated successfully
          schema:
            type: string
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      summary: Update user reading
      tags:
      - User reading
  /api/authors/{bookID}:
    delete:
      consumes:
      - application/json
      description: Deletes user reading from DB. Uses access token from an HTTP-only
        cookie
      parameters:
      - description: Book ID
        in: path
        name: bookID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Deleted successfully
          schema:
            type: string
        "400":
          description: Invalid bookID
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      summary: Delete user reading
      tags:
      - User reading
    get:
      consumes:
      - application/json
      description: Gets one user reading full info from DB. Uses access token from
        an HTTP-only cookie
      parameters:
      - description: Book ID
        in: path
        name: bookID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User reading full info
          schema:
            $ref: '#/definitions/server.ResponseUserReadingFullInfo'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      summary: Get one user reading full info
      tags:
      - User reading
  /ping:
    get:
      consumes:
      - application/json
      description: Checks server health. Returns 200 OK if server is up.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Ping the server
      tags:
      - Health
swagger: "2.0"
